### PR TITLE
fix sar ein

### PR DESCRIPTION
**Pull request by mfdeveloper508**

### CODE REVIEW

**Comment by wadearnold** [comment]
@adamdecaf can you cut a release?

**Comment by adamdecaf** [comment]
This has been released https://github.com/moov-io/fincen/releases/tag/v0.3.3 

Please try it out @mimy2001 and let us know how it works for you!

**Comment by mimy2001** [comment]
@adamdecaf will do, i'm integrating it tonight and we'll test tmr morning and see if it works!

**Comment by mimy2001** [comment]
works well for me

**Pull request merged**
